---
title: "Эконометрика, Осень 2021"
subtitle: "Лекция 6.</br>Нелинейные эффекты в ММЛР"
author: "Владимир Пырлик"
date: "Октябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: section, animated, zoomIn
# Разминка

---
class: section, animated, zoomIn
# Оцнка моделей с нелинейными эффектами

---
class: animated, fadeIn

 $$Y=X'\beta+U$$

--

- решаем, какая д.б. модель

--

- составляем матрицы Y, X

--

- вычисляем $\hat\beta,\;\hat V_{\hat\beta}$

--

## Всё!

### Дальше можем
 - строить ДИ
 - проверять гипотезы
 - интерпретировать результаты
 - ... *всё в зависимости от целей*

---
class: section, animated, fadeIn
# Проверка значимости</br>при нелинейных эффектах

---
class: animated, fadeIn
## .gb[Пример] Рассмотрим модель

$$y_i=\beta_o+\beta_1x_{i1}+\beta_2x_{i2}+\color{red}{\beta_3x_{i1}x_{i2}}+...+u_i,\;\color{blue}{...}$$
**Задача:** проверить значимость эффекта регрессороа $x_1$ .right[.bb[?].rmk[как?]]

--

**Вариант 1:** Проверить $H_o:\{\beta_1=0,\;\beta_3=0\}$ .right[.bb[?].rmk[как?]]

--

**Вариант 2:** Проверить значимость *предельного эффекта* .right[.bb[?].rmk[как?]]

--

 - найти предельный эффект

--

 - проверить значимость 😄

---
class: section, animated, zoomIn
# О немонотонных эффектах

---
class: middle, center, animated, rotateIn
### Lind, J. T., & Mehlum, H. (2010).</br>**With or without U? The appropriate test for a U‐shaped relationship.**</br>*Oxford bulletin of economics and statistics*, 72(1), 109-118.

.gb[О моделировании и проверке немонотонных эффектов]

---
class: animated, fadeIn
## Почему немонотонные эффекты важны?

.center[

.rb[!] Это важный содержательный вопрос во многих контекстах

]

--

</br>

**Варианты вопроса**

 - сохраняется ли эффект при любом масштабе воздействия?

--

 - не наступает ли насыщение / перегиб в эффекте?

--

 - есть ли в перспективе обратный эффект?
 
 - и т.д.

---
class: animated, fadeIn
## Как это замоделировать?

.center[Квадратичная зависимость]

$$y_i=...+\beta_1x_i+\color{red}{\beta_2x_i^2}+...$$

--

</br>

.center[Обратная зависимость]

$$y_i=...+\beta_1x_i+\color{red}{\beta_2x_i^{-1}}+...$$

---
class: animated, fadeIn
## Как проверить значимость?

.rb[!] На практике часто $\color{red}{\text{некорректно}}$ ограничиваются проверкой

$$H_o\:\{\beta_1=0,\;\beta_2=0\}$$

--

</br>

.gb[!] Корректно - проверить **значимость предельного эффекта** .right[.rmk[.bb[?]как?]]

--

- найти предельный эффект

- проверить значимость 😄

--

- правильно интерпретировать .rb[!]


---
class: animated, fadeIn
## Предельный эффект в модели 

$$y_i=...+\beta_1x_i+\color{red}{\beta_2x_i^2}+...$$

$$\frac{\partial\mathbb{E}[y_i|x_i=x]}{\partial x}=\beta_1+2\beta_2x$$

--

### ... и его свойства

$$\sqrt{n}(\hat\beta_1+2\hat\beta_2x-\beta_1-\beta_2x)\xrightarrow[n\to\infty]{d}\mathcal{N}\left(0;[1\;x]\tilde V_{\hat\beta}\left[\begin{matrix}1\\x\end{matrix}\right]\right)$$

--

$$SE(\hat\beta_1+\hat\beta_2x)=\sqrt{\frac{[1\;x]\tilde{\hat V_{\hat\beta}}\left[\begin{matrix}1\\x\end{matrix}\right]}{n}}$$

---
class: animated, fadeIn
## Альтернативный способ

.center[Проверить экстремум] .right[.rmk[.bb[?] как?]]

$$\tilde {\tilde x} = -\frac{\beta_1}{2\beta_2}$$
--

### что с ним делать?

- найти и оценить предельное распределение

- построить ДИ

- интерпретировать

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

