---
title: "Эконометрика, Осень 2021"
subtitle: "Неделя 2. (1) В курсе нотации"
author: "Владимир Пырлик"
date: "Сентябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: section, animated, zoomIn

# Главное правило

---
class: section, animated, flipInY

## Нет абсолютно четких правил!
 
# Читайте внимательно
# **все** условия и пояснения!

---
class: animated, fadeIn
## Случайные величины. Скаляры, векторы и матрицы

.gb[Пример 2.1] Рассмотрим случайную величину
$$X\sim \mathcal{N}(\mu,\sigma^2),$$
с параметрами $\mu\in R$, $\sigma^2\in R^+$...

---
class: animated, fadeIn
## Случайные величины. Скаляры, векторы и матрицы

.gb[Пример 2.2] Мы располагаем данными $\{(y_i,x_i)\}_{i=1,...n}$, где $y_i$ - доход индивида $i$, а $x_i$ - возраст этого индивида... Обозначим вектор возрастов $X=(x_1,...x_n)'$, и $Y=(y_1,...y_n)'$ - вектор доходов...  

---
class: animated, fadeIn
## Случайные величины. Скаляры, векторы и матрицы

.gb[Пример 2.3] Мы располагаем данными $\{(y_i,x_i)\}_{i=1,...n}$, где $y_i$ - доход индивида $i$, а $x_i$ - прочие характеристики индивида - возраст, пол, статус, образование... - всего $k$ характеристик. Запишем доходы индивидов в вектор $Y=(y_1,...y_n)'$, и прочие характеристики в матрицу $X=(x_1,...x_n)'$.

--

$Y$ - вектор (матрица $n\times 1$)

--

$X$ - матрица $n\times k$

--

.rb[NB!] По умолчанию все векторы - столбцы.

---
class: animated, fadeIn
## Переменные и параметры

.gb[Пример 2.4] Рассмотрим несколько вариантов записи одной и той же "модели":
$$x_i=\mu+u_i,$$
где $x_i$ - результат некоторого измерения, $\mu\in R$ - истинное значение измеряемой величины, а $u_i$ - случайная ошибка этого измерения.

--

Для произвольного значения параметра: $x=m+u$

--

В оценках: $x_i=\hat\mu+\hat u_i$

---
class: animated, fadeIn
## Распределения случайных величин

$$z\sim G(\alpha)$$
--

 - $G(z;\alpha)$ - функция распределения (CDF)
 
 - $g(z;\alpha)$ - функция плотности распределения (PDF)
 
 - $G^{-1}(p;\alpha)$ - квантильная функция распределения (QF)

---
class: animated, fadeIn
## Нормальное распределение

$$x\sim \mathcal{N}(\mu,\sigma^2)$$

 - $\Phi_{\mu,\sigma^2}(x)$ - функция нормального распределения
 
 - $\phi_{\mu,\sigma^2}(x)$ - функция плотности нормального распределения
 
 - $\Phi^{-1}_{\mu,\sigma^2}(p)$ - квантильная функция нормального распределения

---
class: animated, fadeIn
## Моменты случайных величин (I)

Рассмотрим случайную величину $X\sim F$. Математическим ожиданием функции $g(.)$ от случайной $X$, $g(X)$, мы называем интеграл

$$\mathbb{E}[g(X)]=\int_{-\infty}^\infty g(x)\text{d}F(x).$$
--

- Математическое ожидание: $\mathbb{E}X$

- Второй момент: $\mathbb{E}X^2$

*и т.д.*

---
class: animated, fadeIn
## Моменты случайных величин (II)

Центральные моменты - это моменты случайной величины, которая предварительно *центрирована*

$$\mathbb{E}[(X-\mathbb{E}X)^k]$$

--

Самый популярный центральный момент - **дисперсия**:

$$\text{Var}X=\mathbb{E}[(X-\mathbb{E}X)^2]$$
---
class: animated, fadeIn
## Моменты случайных величин (III)

.rb[NB!] Математическое ожидание сохраняет размерность!

--

.gb[Пример 2.5] Рассмотрим вектор из двух случайных величин
$$z=(x',y')'.$$

Запишем его математическое ожидание, второй момент и центральынй второй момент. Обсудим устройство третьего момента.

---
class: animated, fadeIn
## Популяция и выборка

.gb[Пример 2.6] Предположим, что мы располагаем выборкой $\{z_i\}_{i=1,...n}$ значений реализаций случайной величины $z$... 

--

.rb[NB!] *"Выборка"* vs *"Случайная выборка"*. **Случайная выборка** подразумевает, что элементы выборки образуют *i.i.d.* последовательность случайных величин (независимых "копий" величины $z$) 


---
class: animated, fadeIn
## Популяционные характеристики и выборочные аналоги
Главный принцип перехода к выборочным аналогам - это "замена" математических ожиданий выборочными средними

$$\mathbb{E}x\;\;\;\;\;\;"\leftrightarrow"\;\;\;\;\;\;\frac{1}{n}\sum_{i=1}^nx_i$$

--

.gb[Пример 2.7] В условиях примера 2.5 мы располагаем выборкой $\{z_i\}_{i=1,...n}$. Каковы будут выборочные аналоги выписанных ранее моментов?

---
class: animated, fadeIn
## Популяционные характеристики и выборочные аналоги

.gb[Пример 2.8] Рассмотрим серию идентичных и независимых испытаний Бернулли с вероятностью успеха $\mu$ (допустим, нам неизвестной). Результаты испытаний фиксируются в наблюдениях $x_i$, где $i$ - номер испытания, $i=1,2...$, и $x_i=1$ в случае успеха и $0$ иначе.

- Разберите ситуацию "по полочкам", по максимуму применив всю разобранную нотацию

---
class: animated, fadeIn
## Популяционные характеристики и выборочные аналоги

.gb[Пример 2.8] Рассмотрим серию идентичных и независимых испытаний Бернулли с вероятностью успеха $\mu$ (допустим, нам неизвестной). Результаты испытаний фиксируются в наблюдениях $x_i$, где $i$ - номер испытания, $i=1,2...$, и $x_i=1$ в случае успеха и $0$ иначе.

- Какие популяционные свойства имеющихся величин наиболее очевидно связаны с неизвестными параметрами?

- Что является выборочным аналогом этих популяционных характеристик?

---
class: animated, fadeIn
## Популяционные характеристики и выборочные аналоги

.gb[Пример 2.8] Рассмотрим серию идентичных и независимых испытаний Бернулли с вероятностью успеха $\mu$ (допустим, нам неизвестной). Результаты испытаний фиксируются в наблюдениях $x_i$, где $i$ - номер испытания, $i=1,2...$, и $x_i=1$ в случае успеха и $0$ иначе.

- Предложите оценку неизвестного параметра методом аналогии и обсудите ее свойства.