---
title: "Эконометрика, Осень 2021"
subtitle: "Неделя 3.</br>(4) Свойства оценок МНК: несмещенность"
author: "Владимир Пырлик"
date: "Сентябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"

---
class: animated, fadeIn
.gb[Пример 3.1 (продолжение)]

$$x_i=\mu+u_i,\;\mathbb{E}u_i=0,\;\{u_i\}_{i=1,...n}\sim\text{i.i.d.},\;\color{blue}{...}$$ 
$$\hat\mu = \frac{1}{n}\sum_{i=1}^nx_i = \color{gray}{...}=\mu+\frac{1}{n}\sum_{i=1}^nu_i.$$

</br>

--

$$\mathbb{E}\hat\mu=\color{gray}{...}=\mu+\frac{1}{n}\sum_{i=1}^n\mathbb{E}u_i=\mu.$$

---
class: animated, fadeIn
## Оценки МНК параметров парной линейной регрессии

$$y_i=\beta_o+\beta_1x_i+u_i,\;\;\;\mathbb{E}[u_i|x_i]=0,\;\;\;\color{blue}{...}$$
</br>

\begin{align}
  \hat\beta_o &= \bar y -\hat\beta_1\cdot\bar x \\\\
  \hat\beta_1 &= \frac{\frac{1}{n}\sum_{i=1}^n\left(y_i-\bar y\right)\left(x_i-\bar x\right)}{\frac{1}{n}\sum_{i=1}^n\left(x_i-\bar x\right)^2}
\end{align}

---
class: animated, fadeIn
## Декомпозиция оценок МНК 

\begin{align}
  \hat\beta_o &= \color{gray}{...} = \beta_o + \color{red}{\textbf{?}}\\
  \hat\beta_1 &= \color{gray}{...} = \beta_1 + \frac{\frac{1}{n}\sum_{i=1}^n\left(\color{blue}{u_i}-\color{blue}{\bar u}\right)\left(x_i-\bar x\right)}{\frac{1}{n}\sum_{i=1}^n\left(x_i-\bar x\right)^2} 
\end{align}

--

</br>
## Несмещенность оценок МНК

\begin{align}
    \mathbb{E}\hat\beta_o &\overset{?}{=} \beta_o, \\
    \mathbb{E}\hat\beta_1 &\overset{?}{=} \beta_1.
\end{align}


---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

