---
title: "Эконометрика, Осень 2021"
subtitle: "Неделя 3. (8) Парная линейная регрессия:</br>эмпирический пример"
author: "Владимир Пырлик"
date: "Сентябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"

---
class: animated, fadeIn
## Вопрос и план

Crampton, E. W. (1947). The growth of the odontoblast of the incisor teeth as a criterion of vitamin *C* intake of the guinea pig. *The Journal of Nutrition*, 33(5), 491–504. [doi: 10.1093/jn/33.5.491](https://doi.org/10.1093/jn/33.5.491)

--

.bb[?] Влияет ли прием витамина *C* на рост зубов?
.right[.rmk[на примере контролируемого эксперимента с морскими свинками]]

--

 - построим и оценим модель парной линейной регрессии

--

 - обсудим интерпретацию оценок

--

 - сделаем выводы на основе статистических тестов
 
--

 - *обсудим альтернативную модель* 

---
class: animated, fadeIn
## Модель и данные

**Предположение:** регулярный прием витамина *C* положительно сказывается на росте зубов, при этом увеличение дозы витамина приводит к пропорциональному росту зубов.

--

$$len = \beta_o+\beta_1dose+u,$$

$$\mathbb{E}[u|dose]=0,\;\;\text{Var}[u|dose]=\sigma^2(dose)<\infty,\;\;\text{Var}\:dose\neq0.$$
--

**Данные:** данные контролируемого эксперимента с морскими свинками

 - $(len_i,dose_i,u_i)\sim \text{i.i.d.}$,
 
 - $n = 60$.

---
class: animated, fadeIn
## Интерпретация модели, ожидаемые результаты

$$len = \beta_o+\beta_1dose+u,\;\;\color{blue}{...}$$

 - модель подразумевает линейную связь
 
 - мы ожидаем положительную связь
 
---
class: animated, fadeIn
## Как это проверить?

 - **интуиция, содержательный анализ** наших представлений о механизме влияния, анализ теории и результатов предыдущих исследований и т.д.
 .right[.rmk[возможно, даже анализ анекдотических свидетельств]]

--

 - **разведывательный анализ данных**
 
--

 - **поверхностный анализ результатов** оценивания модели: соответвтсие оценок ожиданиям, знаки и диапазоны значений оценок коэффициентов и т.д.

--

 - **статистический анализ результатов** оценивания: проверка гипотез о параметрах, анализ доверительных интервалов, построение и анализ прогнозов и т.д.

---
class: section, animated, zoomIn

# Эмпирический
# анализ

---
class: animated, fadeIn
## Статистический анализ эффекта

**Предположение:** регулярный прием витамина *C* положительно сказывается на росте зубов, при этом увеличение дозы витамина приводит к пропорциональному росту зубов.

---
class: animated, fadeIn
## Статистический анализ эффекта

**Предположение:** регулярный прием витамина *C* положительно сказывается на росте зубов...

--

$$H_o:\{\beta_1=0\}$$
.right[.bb[?].rmk[какая должна быть альтернатива?]]

--

$$\textbf{vs}\;\;H_a:\{\beta_1>0\}$$
--

$$t=\frac{\hat\beta_1}{SE(\hat\beta_1)}$$

---
class: animated, fadeIn
## Статистический анализ эффекта

**Предположение:** регулярный прием витамина *C* положительно сказывается на росте зубов...

$$H_o:\{\beta_1=\color{red}0\}$$
.right[.bb[?].rmk[какая должна быть альтернатива?]]

$$\textbf{vs}\;\;H_a:\{\beta_1>\color{red}0\}$$
$$t=\frac{\hat\beta_1\color{red}{-0}}{SE(\hat\beta_1)}$$

---
class: animated, fadeIn
## Статистический анализ эффекта

**Предположение:** регулярный прием витамина *C* положительно сказывается на росте зубов...

$$H_o:\{\beta_1=0\}$$
.right[.bb[?].rmk[какая должна быть альтернатива?]]

$$\textbf{vs}\;\;H_a:\{\beta_1>0\}$$
$$t=\frac{\hat\beta_1}{SE(\hat\beta_1)}$$
$$\text{P-value}=1-\Phi_{0,1}(t).$$

---
class: animated, fadeIn
## Альтернативная модель

**Предположение:** ... кратное увеличение дозы витамина приводит к пропорционально кратному увеличению роста зубов.

--

$$\log(len)=\beta_o+\beta_1\log(dose)+u,\;\;\color{blue}{...}$$
--

$$\beta_1=\frac{\partial\mathbb{E}[\log(len)|dose]}{\partial\log(dose)}$$


