---
title: "Эконометрика, Осень 2021"
subtitle: "Неделя 4.</br>(1) Проблема пропущенной переменной (I)"
author: "Владимир Пырлик"
date: "Сентябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"

---
class: animated, fadeIn
## Попытка парной регрессии для "непарной зависимости"

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\gamma z_i+u_i,\\\mathbb{E}[u_i|x_i,z_i]=0,\;(y_i,x_i,z_i,u_i)\sim\text{i.i.d.},\;\color{blue}{...}\tag{tr}
\end{equation}

--
</br>

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\color{red}{v_i},\\\mathbb{E}[\color{red}{v_i}|x_i]=0,\;(y_i,x_i,\color{red}{v_i})\sim\text{i.i.d.},\;\color{blue}{...}\tag{m1}
\end{equation}

--

$$\color{red}{v_i}=\gamma z_i+u_i\tag{4.1}$$

--
</br>

$$\text{(m1)}\Rightarrow\;\;\hat\beta_1=\frac{\widehat{\text{cov}}(x,y)}{\widehat{\text{Var}}(x)}=\color{gray}{...}=\beta_1+\frac{\widehat{\text{cov}}(x,\color{red}v)}{\widehat{\text{Var}}(x)}$$

---
class: animated, fadeIn
## Попытка парной регрессии для "непарной зависимости"

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\gamma z_i+u_i \tag{tr}
\end{equation}

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\color{red}{v_i} \tag{m1}
\end{equation}

$$\color{red}{v_i}=\gamma z_i+u_i\tag{4.1}$$
$$\text{(m1)}\Rightarrow\;\;\hat\beta_1=\frac{\widehat{\text{cov}}(x,y)}{\widehat{\text{Var}}(x)}=\color{gray}{...}=\beta_1+\frac{\widehat{\text{cov}}(x,\color{red}v)}{\widehat{\text{Var}}(x)}$$

$$\frac{\widehat{\text{cov}}(x,\color{red}v)}{\widehat{\text{Var}}(x)} \xrightarrow[n\to\infty]{p}\frac{{\text{cov}}(x,\color{red}v)}{{\text{Var}}(x)} \overset{\color{blue}{\textbf{?}}}{=}0$$

---
class: animated, fadeIn
## Попытка парной регрессии для "непарной зависимости"

$$\text{cov}(x,\color{red}v)=\text{cov}(x,\gamma z+u)=...=\gamma\text{cov}(x,z)+\underset{\color{gray}{=0}}{\color{gray}{\text{cov}(x,u)}}$$

--

$$\text{cov}(x,\color{red}v)=0,\text{если}$$
$$\text{либо}\;\gamma=0,\;\text{либо}\;\text{cov}(x,z)=0.$$
---
class: animated, fadeIn
## Попытка парной регрессии для "непарной зависимости"

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\gamma z_i+u_i,\\\mathbb{E}[u_i|x_i,z_i]=0,\;(y_i,x_i,z_i,u_i)\sim\text{i.i.d.},\;\color{blue}{...}\tag{tr}
\end{equation}

</br>

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\color{red}{v_i},\\\mathbb{E}[\color{red}{v_i}|x_i]=0,\;(y_i,x_i,\color{red}{v_i})\sim\text{i.i.d.},\;\color{blue}{...}\tag{m1}
\end{equation}

$$\color{red}{v_i}=\gamma z_i+u_i\tag{4.1}$$

---
class: animated, fadeIn
## Попытка парной регрессии для "непарной зависимости"

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\color{white}{\gamma z_i+}u_i,\\\mathbb{E}[u_i|x_i,z_i]=0,\;(y_i,x_i,\color{white}{z_i,}u_i)\sim\text{i.i.d.},\;\color{blue}{...}\tag{tr}
\end{equation}

</br>

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\color{red}{v_i},\\\mathbb{E}[\color{red}{v_i}|x_i]=0,\;(y_i,x_i,\color{red}{v_i})\sim\text{i.i.d.},\;\color{blue}{...}\tag{m1}
\end{equation}

$$\color{red}{v_i}=\color{white}{\gamma z_i+}u_i\tag{4.1}$$

</br>

$$\text{(tr)}\;\Leftrightarrow\;\text{(m1)}$$
---
class: animated, fadeIn
## Попытка парной регрессии для "непарной зависимости"

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\gamma z_i+u_i,\\\mathbb{E}[u_i|x_i,z_i]=0,\;(y_i,x_i,z_i,u_i)\sim\text{i.i.d.},\;\color{blue}{...}\tag{tr}
\end{equation}

</br>

\begin{equation}
  y_i=\beta_o+\beta_1x_i+\color{red}{v_i},\\\mathbb{E}[\color{red}{v_i}|x_i]=0,\;(y_i,x_i,\color{red}{v_i})\sim\text{i.i.d.},\;\color{blue}{...}\tag{m1}
\end{equation}

$$\color{red}{v_i}=\gamma z_i+u_i\tag{4.1}$$

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

