---
title: "Эконометрика, Осень 2021"
subtitle: "Неделя 4. (8) **ММЛР:** свойства оценок МНК (I)"
author: "Владимир Пырлик"
date: "Сентябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"
---
class: animated, fadeIn
## Параметры ММЛР: популяционная характеристика и оценки

$$y_i = x_i'\beta+u_i, \color{blue}{...}\;\;\color{white}{\text{или}\;\;Y=X\beta+U,\;...}$$
---
class: animated, fadeIn
## Параметры ММЛР: популяционная характеристика и оценки

$$y_i = x_i'\beta+u_i, \color{blue}{...}\;\;\text{или}\;\;Y=X\beta+U,\;\color{blue}{...}$$

--

\begin{align}
  \beta     &= Q_{xx}^{-1}Q_{xy}\color{white}{.................}
\end{align}

---
class: animated, fadeIn
## Параметры ММЛР: популяционная характеристика и оценки

$$y_i = x_i'\beta+u_i, \color{blue}{...}\;\;\text{или}\;\;Y=X\beta+U,\;\color{blue}{...}$$

\begin{align}
  \beta     &= Q_{xx}^{-1}Q_{xy}\color{white}{.................}\\\\
  \hat\beta &= \hat Q_{xx}^{-1}\hat Q_{xy} = \\
            &= (X'X)^{-1}X'Y 
\end{align}

---
class: animated, fadeIn
## Параметры ММЛР: популяционная характеристика и оценки

$$y_i = x_i'\beta+u_i, \color{blue}{...}\;\;\text{или}\;\;Y=X\beta+U,\;\color{blue}{...}$$



\begin{align}
  \beta     &= Q_{xx}^{-1}Q_{xy}\color{white}{.................}\\\\
  \hat\beta &= \hat Q_{xx}^{-1}\hat Q_{xy} = \\
            &= (X'X)^{-1}X'Y = \\\\
            &= \beta + \hat Q_{xx}^{-1} \hat Q_{xu} = \\
            &= \beta + (X'X)^{-1}X'U
\end{align}

---
class: animated, fadeIn
## ММЛР: свойства оценок МНК

 - состоятельность

--

 - несмещенность

--

 - асимптотическая нормальность

---
class: animated, fadeIn
## Состоятельность оценок МНК ММЛР

**Два способа показать**

 - напрямую для выборочного аналога популяционной характеристики паарметров
 
--

 - для декомпозиции оценки .rb[ДЗ]

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

