---
title: "Эконометрика, Осень 2021"
subtitle: "Неделя 3. (5) Свойства оценок МНК:</br>асимптотическое распределение"
author: "Владимир Пырлик"
date: "Сентябрь 2021"
output:
  xaringan::moon_reader:
    mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_HTMLorMML"
    lib_dir: libs
    css: [libs/main.css, libs/fonts.css, libs/animate.css]
    chakra: libs/remark-latest.min.js
    nature:
      highlightStyle: github
      countIncrementalSlides: false
      highlightLines: true
      ratio: "8:5"

---
class: animated, fadeIn
.gb[Пример 3.1 (продолжение)]

$$x_i=\mu+u_i,\;\mathbb{E}u_i=0,\;\{u_i\}_{i=1,...n}\sim\text{i.i.d.},\;\color{blue}{...}$$ 
$$\hat\mu = \frac{1}{n}\sum_{i=1}^nx_i = \color{gray}{...}=\mu+\frac{1}{n}\sum_{i=1}^nu_i.$$

--

$$\hat\mu - \mu = \frac{1}{n}\sum_{i=1}^nu_i$$

---
class: animated, fadeIn
.gb[Пример 3.1 (продолжение)]

$$x_i=\mu+u_i,\;\mathbb{E}u_i=0,\;\{u_i\}_{i=1,...n}\sim\text{i.i.d.},\;\color{blue}{...}$$ 
$$\hat\mu = \frac{1}{n}\sum_{i=1}^nx_i = \color{gray}{...}=\mu+\frac{1}{n}\sum_{i=1}^nu_i.$$

$$\color{blue}{\sqrt{n}}(\hat\mu - \mu) = \color{blue}{\sqrt{n}}\left(\frac{1}{n}\sum_{i=1}^nu_i\;-\;0\right)$$

---
class: animated, fadeIn
.gb[Пример 3.1 (продолжение)]

$$x_i=\mu+u_i,\;\mathbb{E}u_i=0,\;\{u_i\}_{i=1,...n}\sim\text{i.i.d.},\;\color{blue}{...}$$ 
$$\hat\mu = \frac{1}{n}\sum_{i=1}^nx_i = \color{gray}{...}=\mu+\frac{1}{n}\sum_{i=1}^nu_i.$$

$$\color{blue}{\sqrt{n}}(\hat\mu - \mu) = \color{blue}{\sqrt{n}}\left(\frac{1}{n}\sum_{i=1}^nu_i\;-\;0\right) \xrightarrow[n\to\infty]{\color{red}d}\mathcal{N}(0;\;\text{Var}\:u_i)$$

---
class: animated, fadeIn
## Декомпозиция оценок МНК парной линейной регрессии  

\begin{align}
  \hat\beta_o &= \color{gray}{...} = \beta_o + \color{red}{\textbf{?}}\\
  \hat\beta_1 &= \color{gray}{...} = \beta_1 + \frac{\frac{1}{n}\sum_{i=1}^n\left(\color{blue}{u_i}-\color{blue}{\bar u}\right)\left(x_i-\bar x\right)}{\frac{1}{n}\sum_{i=1}^n\left(x_i-\bar x\right)^2} 
\end{align}

--

</br>
## Асимптотическое распределение оценок МНК

\begin{align}
    \sqrt{n}(\hat\beta_o -\beta_o) \xrightarrow[n\to\infty]{d}\mathcal{N}(0;\; \color{red}{\textbf{?}}) \\
    \sqrt{n}(\hat\beta_1 -\beta_1) \xrightarrow[n\to\infty]{d}\mathcal{N}(0;\; \color{red}{\textbf{?}})
\end{align}


---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

---
class: animated, fadeIn
## 

